Fix problems due to integer bit width or signedness
/home/richie/flexric/examples/xApp/c/orange/xapp_es_with_cell_util.c:1374:17: error: passing argument 1 of ‘forEachCell’ from incompatible pointer type [-Wincompatible-pointer-types]
 1374 |     forEachCell(getTargetCellID, doHandoverAction, switchOffCurrentCell, context);
      |                 ^~~~~~~~~~~~~~~
      |                 |
      |                 uint8_t (*)(callback_data_t) {aka unsigned char (*)(callback_data_t)}
/home/richie/flexric/examples/xApp/c/orange/xapp_es_with_cell_util.c:1155:27: note: expected ‘Callback’ {aka ‘short unsigned int (*)(callback_data_t)’} but argument is of type ‘uint8_t (*)(callback_data_t)’ {aka ‘unsigned char (*)(callback_data_t)’}
 1155 | void forEachCell(Callback targetCellFinding, Callback cbHOAction, Callback cbSwitchOffAction, callback_data_t data)
      |                  ~~~~~~~~~^~~~~~~~~~~~~~~~~

      warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]